language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '10'
addons:
  apt:
    packages:
    - redis-server
script:
  - npm run lint
  - (redis-server & )
  - npm test
cache: npm
notifications:
  email:
    on_success: never
